CREATE TABLE IF NOT EXISTS CUSTOMER
(
    ID NUMBER(10,0) NOT NULL,
    USER_NAME VARCHAR2(60) NOT NULL,
    PASSWORD VARCHAR2(60) NOT NULL,
    EMAIL VARCHAR2(60) NOT NULL,
    STREET VARCHAR2(60) NOT NULL,
    CITY VARCHAR2(60) NOT NULL,
    DISTRICT VARCHAR2(60) NOT NULL,
    CEP VARCHAR2(8) NOT NULL,
    UF VARCHAR2(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORY
(
    ID NUMBER(10,0) NOT NULL,
    NAME VARCHAR2(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT
(
    ID NUMBER(10,0) NOT NULL,
    DESCRIPTION VARCHAR2(60) NOT NULL,
    QUANTITY NUMBER(10,1) NOT NULL,
    PRICE NUMBER(10,1) NOT NULL,
    ID_CATEGORY NUMBER(10,1) NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDER_ALL
(
    ID NUMBER(10,0) NOT NULL,
    DATE_REQUEST DATE NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    SESSION_ID VARCHAR2(60) NOT NULL,
    CUSTOMER_ID NUMBER(10,1) NOT NULL
);

CREATE TABLE IF NOT EXISTS ITEM
(
    ID NUMBER(10,0) NOT NULL,
    DESCRIPTION VARCHAR2(60) NOT NULL,
    ID_PRODUCT NUMBER(10,1) NOT NULL,
    ID_ORDER NUMBER(10,1) NOT NULL,
    QUANTITY NUMBER(10,1) NOT NULL,
    PRICE DECIMAL(20, 2) NOT NULL,
    SUBTOTAL DECIMAL(20, 2) NOT NULL
);